### ISSUE TITLE
Question: That composition happens on Presentation Layer or on Gateway?

### ISSUE THREAD

**Issue by dmitribodiu** [ServiceComposer/ServiceComposer.AspNetCore#119]
Can we use same technique witch SPA on React? I'm wondering, that composition should happen on presentation layer, or it can be a gateway? If it is a gateway, and its down, feels like all services would become unavailable, or that's not an issue?

**Comment by mauroservienti** [comment]
First of all thanks for your immense patience. Crazy times.

> Can we use same technique witch SPA on React?

Yes, my original implementation was for AngularJs 1.x. The logic is essentially the same, the toolchain obviously might affect some of the design.

> I'm wondering, that composition should happen on presentation layer, or it can be a gateway? If it is a gateway, and its down, feels like all services would become unavailable, or that's not an issue?

That's a good point. I think we need to first define what kind of "layers" we're discussing here. If they are physical layers then there is only a technical difference between implementing this at the presentation layer or at the gateway. If we're talking about logical layers then the gateway is part of the presentation layer making it irrelevant where the implementation is crafted.

The composition gateway should be (and I see no good reasons why it shouldn't) stateless, which means that it can be made highly available and horizontally scaled out making the "it's down" problem less relevant. where to implement the composition is a decision driven by multiple factors, there is no ubiquitous answer. For example:

- are clients only desktop machines on a high bandwidth connection? It might make sense to implement the composition process at the browser/client level (e.g. in React)
- are client mobile devices only? Implementing composition at the client might mean a lot of outgoing connections which might have a significant impact on the overall performance on low bandwidth/high latency connections
- are the client technologically homogenous (e.g. all browsers and all React)? then implement in the client; otherwise, move the composition to the gateway to shield it from different technology stacks used at the clients

These are just a few out of a lot of consideration that needs to be made. There might be even cases in which a mixed scenario makes sense.

In any case, I don't see the availability of the gateway as an issue. It's more of an operations problem that when dealing with a stateless component can be "easily" addressed.

Toughts?
